project_name: lazynode

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/lazynode/main.go
    ldflags:
      - -s -w -X github.com/VesperAkshay/lazynode/pkg/version.Version={{.Version}}
    binary: lazynode

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

brews:
  - name: lazynode
    tap:
      owner: VesperAkshay
      name: homebrew-lazynode
    homepage: "https://github.com/VesperAkshay/lazynode"
    description: "A powerful TUI for managing Node.js projects"
    license: "MIT"

scoop:
  bucket:
    owner: VesperAkshay
    name: scoop-bucket
  homepage: "https://github.com/VesperAkshay/lazynode"
  description: "A powerful TUI for managing Node.js projects"
  license: MIT 